autoscaling:
  enabled: false

replicaCount: "2"

image: 
  repository: 12345.dkr.ecr.eu-west-2.amazonaws.com/app2
  tag: "484309960e4294189d5a1253924fa29e8ad8dba6-prod"
  pullPolicy: "Always"

service:
  type: ClusterIP
  enabled: true
  port: 6000
  targetPort: 8080

env:
  MY_ENV_VAR: "1"

secenv:
  MY_SECRET: "2"

configenv:
  MY_CONFIG_MAP_ENV_VAR: "3"



resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 50m
    memory: 64Mi

readinessCheck:
  readinessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 3
livenessCheck:
  livenessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6