apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "generic.fullname" . }}
    version: "{{ .Values.image.tag | default .Chart.AppVersion }}"
    {{- include "generic.labels" . | nindent 4 }}
    {{- with .Values.deploymentLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generic.selectorLabels" . | nindent 6 }}
  {{- with .Values.updateStrategy }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  template:
    metadata:
      annotations:
        co.elastic.logs.{{ include "generic.fullname" . }}-service/enabled: "true"
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "generic.fullname" . }}
        version: "{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{- include "generic.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.additionalPodYaml }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ include "generic.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainers }}
      initContainers:
      {{- with .Values.initContainers }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ include "generic.fullname" . }}-service
        {{- if or .Values.configMap.envFrom .Values.configMap.enabled .Values.configenv .Values.secenv }}
          envFrom: 
        {{- end }}  
        {{- if .Values.configenv }}
          - configMapRef:
              name: {{ include "generic.fullname" . }}-configmap
        {{- end }}  
        {{- if .Values.secenv }}
          - secretRef:
              name: {{ include "generic.fullname" . }}-secenv
        {{- end }}  
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if .Values.env }}
          env:
          {{- range $name, $value := .Values.env }}
          {{- if not (empty $value) }}
          - name: {{ $name | quote }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- end }}
          # Params for env vars populated from k8s secrets
          {{- if .Values.envVarsFromSecret }}
          {{- range $key, $value := .Values.envVarsFromSecret }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $value.secretKeyRef | quote }}
                key: {{ $value.key | quote }}
          {{- end }}
          {{- end }}
          {{- if or .Values.filesFromSecret .Values.extraVolumeMounts }}
          {{- if .Values.extraVolumeMounts }}
          {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- end }}
          {{- with .Values.filesFromSecret }}
          {{- range $key, $value := . }}
          - name: {{ $key }}
            mountPath: {{ $value.mountPath }}
            readOnly: true
          {{- end }}
          {{- end }}
          {{- end }}
          {{- with .Values.readinessCheck }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.livenessCheck }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.redisSidecar.enabled }}
        - name: {{ include "generic.fullname" . }}-redis
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.redisSidecar.image }}"
          imagePullPolicy: {{ .Values.redisSidecar.pullPolicy }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.redisSidecar.targetPort }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.redisSidecar.targetPort }}
            periodSeconds: {{ .Values.redisSidecar.livenessInterval }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.filesFromSecret .Values.extraVolumes }}
      volumes:
      {{- if .Values.extraVolumes }}
      {{- toYaml .Values.extraVolumes | nindent 8 }}
      {{- end }}
      {{- with .Values.filesFromSecret }}
      {{- range $key, $value := . }}
      - name: {{ $key }}
        secret:
          secretName: {{ $value.secret }}
      {{- end }}
      {{- end }}
      {{- end }}
