{{- if and .Values.app.services .Values.app.services.enabled }}
{{- range .Values.app.services.list }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .name }}"
  namespace: "{{ .namespace | default $.Release.Namespace }}"
  labels:
    {{- if .labels }}
    {{ .labels | toYaml | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .annotations }}
    {{ .annotations | toYaml | nindent 4 }}
    {{- else }}
    {}
    {{- end }}
spec:
  {{- if .spec.clusterIP }}
  clusterIP: {{ .spec.clusterIP }}
  {{- end }}
  {{- if .spec.clusterIPs }}
  clusterIPs:
  {{ .spec.clusterIPs | toYaml | nindent 2 }}
  {{- end }}
  internalTrafficPolicy: {{ .spec.internalTrafficPolicy | default "Cluster" }}
  {{- if .spec.ipFamilies }}
  ipFamilies:
  {{ .spec.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ipFamilyPolicy: {{ .spec.ipFamilyPolicy | default "SingleStack" }}
  ports:
    {{- range .spec.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  {{- if .spec.publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ .spec.publishNotReadyAddresses }}
  {{- end }}
  selector:
    {{- if .spec.selector }}
    {{ .spec.selector | toYaml | nindent 4 }}
    {{- end }}
  sessionAffinity: {{ .spec.sessionAffinity | default "None" }}
  type: {{ .spec.type | default "ClusterIP" }}
{{- end }}
{{- end }}