apiVersion: v2
name: miaplaza-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: regulator
    version: 0.1.0
    repository: "file://../sub-charts/regulator"

  - name: mariadb
    alias: wp-careers-mariadb
    version: 20.2.1
    repository: "https://charts.bitnami.com/bitnami"
  - name: wp-careers-wordpress
    version: 0.1.0
    repository: "file://../sub-charts/wp-careers-wordpress"

  - name: mariadb
    alias: wp-miaprep-homeschool-curriculum-mariadb
    version: 20.2.1
    repository: "https://charts.bitnami.com/bitnami"
  - name: wp-miaprep-homeschool-curriculum-wordpress
    version: 0.1.0
    repository: "file://../sub-charts/wp-miaprep-homeschool-curriculum-wordpress"

  - name: rabbitmq
    alias: rabbitmq
    version: 15.2.1
    repository: "https://charts.bitnami.com/bitnami"

  - name: redis
    alias: miacademy-redis-master
    version: 20.6.1
    repository: "https://charts.bitnami.com/bitnami"

  - name: miacademy-website
    version: 0.1.0
    repository: "file://../sub-charts/miacademy-website"