miacademy-main:
  image:
    registry: registry.dev.miaplaza.com
    repository: infrastructure/postgresql
    tag: "15-6-0-0"
    pullSecrets:
      - name: miaplaza-website-registry
      - name: infrastructure-postgresql-registry
      - name: infrastructure-nginx-registry
  global:
    security:
      allowInsecureImages: true
    postgresql:
      auth:
        database: "miaplaza"
  fullnameOverride: "miacademy-main"
  primary:
    nodeSelector:
      role: postgres
  metrics:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/postgres-exporter
      tag: 0.10.0-debian-10-r172
    extendedConfiguration:
      archive_command = 'pgbackrest --stanza=postgres archive-push %p'
      archive_mode = 'on'
      effective_cache_size = '18868MB'
      jit = 'off'
      maintenance_work_mem = '1024MB'
      max_connections = 576
      max_wal_senders = 3
      random_page_cost = '0.7'
      seq_page_cost = '0.5'
      shared_buffers = '8938MB'
      timezone = 'Europe/Berlin'
      work_mem = '54MB'

miacademy-writemostly:
  image:
    registry: registry.dev.miaplaza.com
    repository: infrastructure/postgresql
    tag: "15-6-0-0"
    pullSecrets:
      - name: miaplaza-website-registry
      - name: infrastructure-postgresql-registry
      - name: infrastructure-nginx-registry
  global:
    security:
      allowInsecureImages: true
    postgresql:
      auth:
        database: "miaplaza"
  fullnameOverride: "miacademy-writemostly"
  primary:
    nodeSelector:
      role: postgres
  metrics:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/postgres-exporter
      tag: 0.10.0-debian-10-r172
    extendedConfiguration:
      archive_command = 'pgbackrest --stanza=postgres archive-push %p'
      archive_mode = 'on'
      effective_cache_size = '18868MB'
      jit = 'off'
      maintenance_work_mem = '1024MB'
      max_connections = 576
      max_wal_senders = 3
      random_page_cost = '0.7'
      seq_page_cost = '0.5'
      shared_buffers = '8938MB'
      timezone = 'Europe/Berlin'
      work_mem = '54MB'


wp-careers-mariadb:
  auth:
    username: bn_wordpress
    database: bitnami_wordpress
    password: mypassword
    rootPassword: HELIUUgQFJ

wp-careers-wordpress:
  fullnameOverride: "wp-careers-wordpress"
  mariadb:
    auth:
      existingSecret: miacademy-wp-careers-mariadb

wp-miaprep-homeschool-curriculum-mariadb:
  auth:
    username: bn_wordpress
    database: bitnami_wordpress
    password: mypassword
    rootPassword: krU82NJNQS

wp-miaprep-homeschool-curriculum-wordpress:
  fullnameOverride: "wp-miaprep-homeschool-curriculum-wordpress"
  mariadb:
    auth:
      existingSecret: miacademy-wp-miaprep-homeschool-curriculum-mariadb

rabbitmq:
  auth:
    username: miaplaza

website-redis:
  global:
    redis:
        password: GeKDAvBsDE
