---
{{- if and .Values.configMaps.enabled .Values.configMaps.list }}
{{- range .Values.configMaps.list }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .name }}"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    {{- include "generic.labels" $ | nindent 4 }}
    {{- if .labels }}
    {{ toYaml .labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .annotations }}
    {{ toYaml .annotations | nindent 4 }}
    {{- else }}
    {}
    {{- end }}
data:
  {{- if .files }}
  {{- range $key, $value := .files }}
  {{ $key }}: |-
{{ $value | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
