{{- if .Values.secrets }}
{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .name }}"
  namespace: "{{ .namespace | default $.Release.Namespace }}"
  labels:
    {{- include "generic.labels" $ | nindent 4 }}
  annotations:
    {{- if .annotations }}
    {{ toYaml .annotations | nindent 4 }}
    {{- else }}
    {}
    {{- end }}
type: "{{ .type | default "Opaque" }}"
data:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
