# See ../../charts/ingress-nginx/values.yaml for full list of features

image:
  name: nginx
  tag: 1.22.0
  pullPolicy: IfNotPresent

livenessProbe:
  httpGet:
    path: /healthz
    port: 80
  initialDelaySeconds: 15
  periodSeconds: 3

services:
  - name: "http" # name "http" binds to http listeners 
    type: NodePort
    nodePort: 30080
    containerPort: 80
  - name: "https" # name "https" binds to https listeners 
    type: NodePort
    nodePort: 30443
    containerPort: 443

rollingUpdateMaxUnavailable: 1 # 1 is the minimum available value for this field when using DaemonSet

ssl:
  enabled: true