# See ../../charts/ingress-nginx/values.yaml for full list of features

image:
  name: nginx
  tag: 1.21.6
  pullPolicy: IfNotPresent

services:
  - name: "http" # name "http" binds to http listeners 
    type: HostPort
    hostPort: 80
    containerPort: 80
  - name: "https" # name "https" binds to https listeners 
    type: HostPort
    hostPort: 443
    containerPort: 443

rollingUpdateMaxUnavailable: 1 # 1 is the minimum available value for this field when using DaemonSet
