image:
  registry: registry.dev.miaplaza.com
  repository: infrastructure/postgresql
  tag: "15-6-0-0"
  pullSecrets:
    - name: miaplaza-website-registry
    - name: infrastructure-postgresql-registry
    - name: infrastructure-nginx-registry
global:
  security:
    allowInsecureImages: true
  postgresql:
    auth:
      database: "miaplaza"
fullnameOverride: "miacademy-main"
primary:
  nodeSelector:
    role: postgres
  extendedConfiguration: |-
    archive_command = 'pgbackrest --stanza=postgres archive-push %p'
    archive_mode = 'on'  # Temporarily disable to debug
    effective_cache_size = '18868MB'
    jit = 'off'
    maintenance_work_mem = '512MB'  # Reduce for high concurrency
    max_connections = 200  # Temporarily reduce for debugging
    max_wal_senders = 3
    random_page_cost = '0.7'
    seq_page_cost = '0.5'
    shared_buffers = '4096MB'  # Reduce to match container memory limits
    timezone = 'Europe/Berlin'
    work_mem = '16MB'  # Reduce to avoid excessive memory usage

metrics:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/postgres-exporter
    tag: 0.10.0-debian-10-r172

